### PR TITLE
Handle sort plan creation in query planner depending on GROUP BY/DISTINCT

### PR DESCRIPTION
**Pull request by don-tay**
## Changes in this PR

- [x] Bug fix
- [ ] New feature
- [ ] Breaking change of an existing feature
- [ ] Refactor/Performance enhancements

## Overview

- Handle sort plan creation in table planner depending if group by / distinct is present (see comments below for more info)

This fixes following query (in #35):
```
select dname,count(sid) from student, dept where majorid=did group by dname order by dname desc
```
```
 dname countofsid
-----------------
 math         4
drama         6
compsci         7
```

### CODE REVIEW

**Comment by don-tay** [comment]
However, sort using `ORDER BY` will still fail to work if `DISTINCT` is used, because `DISTINCT` further re-orders the fields.

**Review by tishyakhanna97 — APPROVED** [review]
NICE CATCH!!!!

**Comment by don-tay** [comment]
In terms of implementation, this means 2 cases:
1. If group by or distinct field is available, push sort plan to be created at the end.
2. Else, sort plan should be created BEFORE project plan

**Comment by don-tay** [comment]
Behaviour above now implemented:
Test queries:
```
SQL> select distinct sname from student order by sid
 sname
------
java.lang.RuntimeException: field sid not found.
        at simpledb.query.DistinctScan.getVal(DistinctScan.java:101)
        at simpledb.materialize.RecordComparator.compare(RecordComparator.java:41)
        at simpledb.materialize.SortPlan.splitIntoRuns(SortPlan.java:102)
        at simpledb.materialize.SortPlan.open(SortPlan.java:42)
        at test.SimpleIJ.doQuery(SimpleIJ.java:69)
        at test.SimpleIJ.main(SimpleIJ.java:39)
transaction 2 rolled back

SQL> select sname from student group by sname order by sid
 sname
------
java.lang.RuntimeException: field sid not found.
        at simpledb.materialize.GroupByScan.getVal(GroupByScan.java:93)
        at simpledb.materialize.RecordComparator.compare(RecordComparator.java:41)
        at simpledb.materialize.SortPlan.splitIntoRuns(SortPlan.java:102)
        at simpledb.materialize.SortPlan.open(SortPlan.java:42)
        at simpledb.plan.ProjectPlan.open(ProjectPlan.java:32)
        at test.SimpleIJ.doQuery(SimpleIJ.java:69)
        at test.SimpleIJ.main(SimpleIJ.java:39)
transaction 2 rolled back
```

**Pull request merged**
