### PR TITLE
Feature/join optimization

### PR DESCRIPTION
**Pull request by don-tay**
## Changes in this PR

- [ ] Bug fix
- [x] New feature
- [ ] Breaking change of an existing feature
- [ ] Refactor/Performance enhancements

## Overview

- Pick the join implementation which yields the least output records

### CODE REVIEW

**Comment by don-tay** [comment]
Should we optimize for the least block access instead? @xinyee20 @tishyakhanna97

**Review by tishyakhanna97 — APPROVED** [review]
lgtm

**Comment by xinyee20** [comment]
> Should we optimize for the least block access instead? @xinyee20 @tishyakhanna97

Yup, I think that will be better!

**Review by xinyee20 — APPROVED** [review]
recordoutputs work too, lgtm!

**Comment by don-tay** [comment]
When idx on sid:
```
SQL> select sid, sname, eid from student, enroll where sid = studentid
p1Cost: 12 p2Cost: 17 p3Cost: 102
Running index join
 sid sname eid
--------------
  1  joe 14
  1  joe 24
  2  amy 34
  4  sue 44
  4  sue 54
  6  kim 64
```
When no idx on sid:
```
SQL> select sid, sname, eid from student, enroll where sid = studentid
p1Cost: 2147483647 p2Cost: 17 p3Cost: 102
Running sort merge
 sid sname eid
--------------
  1  joe 14
  1  joe 24
  2  amy 34
  4  sue 44
  4  sue 54
  6  kim 64
```

**Pull request merged**
